image: node:latest
before_script:
  - curl https://get.volta.sh | bash

cache:
  paths:
    - node_modules/
    - .yarn

build:
  stage: build
  artifacts:
    paths:
      - dist/
      - creevey-*.tgz
  script:
    - yarn lint
    - yarn build
    - yarn pack
unit:
  script:
    - yarn test:unit

ui:
  stage: test
  services:
    - selenoid/chrome
    - selenoid/firefox
  dependencies:
    - build
  artifacts:
    when: always
    paths:
      - report/
  script:
    - mkdir report
    - cp dist/client/web/*.js report/
    - yarn start:storybook &
    - yarn creevey:gitlab
