image: node:20

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - .yarn/

before_script:
  - corepack enable
  - yarn

build:
  stage: build
  artifacts:
    paths:
      - dist/
      - package.tgz
  script:
    - yarn build
    - yarn lint
    - yarn pack

tests:
  stage: test
  artifacts:
    when: always
    paths:
      - report/
    reports:
      junit: report/junit.xml
  script:
    - yarn playwright install --with-deps chromium firefox
    - yarn build
    - yarn test
    - yarn build-storybook --test
    - yarn http-server storybook-static --port 6006 --silent &
    - SERVER_PID=$!
    - trap 'kill $SERVER_PID' EXIT
    - yarn creevey:gitlab
