name: Build and Test
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        with:
          registry-url: https://registry.npmjs.org
      - name: install
        run: yarn
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: pack
        run: yarn pack
      - uses: actions/upload-artifact@v4
        with:
          name: creevey
          path: package.tgz
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: volta-cli/action@v4
        with:
          registry-url: https://registry.npmjs.org
      - name: checkout lfs
        run: git lfs checkout
      - name: install
        run: yarn
      - name: unit tests
        run: yarn test
      - name: storybook
        run: yarn start:storybook &
      - name: creevey
        run: yarn creevey:github
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: report/
